config/routes.rb
Rails.application.routes.draw do
  
  resources :vans
  resources :books
  resources :rentals
  resources :items
  get 'user_management/assign_roles'
  patch 'user_management/update'
  get 'user_management/show'
  get 'user_management/edit'
  get 'user_management/create'
  post 'user_management/update'
  get 'user_management/new'
  post 'user_management/create'
  get 'item/available'
  resources :roles
  get 'home/index'
  get 'user_management/find_current_user'
  devise_for :users, :controllers => { :registrations => "users/registrations" }, :path_prefix => 'my'
  resources :users
  as :user do
    get "/register", to: "registrations#new", as: "register"
  end

  root to: "home#index"

end

app/models/van.rb
class Van < ApplicationRecord
    has_many :rentals, as: :rentable, dependent: :destroy
    has_many :users, through: :rentals
end

app/controllers/vans_controller.rb
class VansController < ApplicationController
  before_action :authenticate_user!
  before_action :set_van, only: %i[ show edit update destroy ]

  def index
    @vans = Van.all
    @availables = is_available
  end

  def show
    @rentals = Rental.where(rentable_id: params[:id])
    @available = true
    @rentals.each do |rentalx|
      if rentalx.return_date.nil?
        @available = false
      else
        if rentalx.return_date.future?
          @available = false
        end
      end
    end
  end

  def new
    @van = Van.new
  end

  def edit
  end

  def create
    @van = Van.new(van_params)
    @van.name = @van.vyear.to_s + " " + @van.vmake + " " + @van.vmodel
    respond_to do |format|
      if @van.save
        format.html { redirect_to van_url(@van), notice: "Van was successfully created." }
        format.json { render :show, status: :created, location: @van }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @van.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      @van.name = @van.vyear.to_s + " " + @van.vmake + " " + @van.vmodel
      if @van.update(van_params)
        format.html { redirect_to van_url(@van), notice: "Van was successfully updated." }
        format.json { render :show, status: :ok, location: @van }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @van.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @van.destroy

    respond_to do |format|
      format.html { redirect_to vans_url, notice: "Van was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def is_available
    @vans = Van.all
    available_vans = []
    @vans.each do |vanx|
      van_rentals = Rental.where(rentable_type: "Van", rentable_id: vanx.id)
      available = true
      van_rentals.each do |rentalx|
        if rentalx.return_date.nil? || rentalx.return_date.future?
          available = false
        end
      end
      available_vans << available
    end
    return available_vans
  end

  private
    def set_van
      @van = Van.find(params[:id])
    end

    def van_params
      params.require(:van).permit(:vyear, :vmake, :vmodel, :notes)
    end
end

app/helpers/vans_helper.rb
module VansHelper
end

app/views/vans/_form.html.erb
<%= form_with(model: van) do |form| %>
  <% if van.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(van.errors.count, "error") %> prohibited this van from being saved:</h2>

      <ul>
        <% van.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :van_year %>
    <%= form.number_field :vyear %>
  </div>

  <div class="field">
    <%= form.label :van_make %>
    <%= form.text_field :vmake %>
  </div>

  <div class="field">
    <%= form.label :van_model %>
    <%= form.text_field :vmodel %>
  </div>

  <div class="field">
    <%= form.label :notes %>
    <%= form.text_area :notes %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/vans/edit.html.erb
<h1>Editing Van</h1>

<%= render 'form', van: @van %>

<%= link_to 'Show', @van %> |
<%= link_to 'Back', vans_path %>

app/views/vans/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Vans</h1>

<table class="table">
  <thead>
    <tr>
      <th>Van Year</th>
      <th>Van Make</th>
      <th>Van Model</th>
      <th>Notes</th>
      <th>Id</th>
      <th>Availability</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @vans.each_with_index do |vanx, index| %>
      <tr>
        <td><%= vanx.vyear %></td>
        <td><%= vanx.vmake %></td>
        <td><%= vanx.vmodel %></td>
        <td><%= vanx.notes %></td>
        <td><%= vanx.id %></td>
        <td><%= @availables[index] %></td>
        <td><%= link_to 'Show', vanx %></td>
        <td><%= link_to 'Edit', edit_van_path(vanx) %></td>
        <td><%= link_to 'Destroy', vanx, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<%= link_to 'New Van', new_van_path %>

app/views/vans/new.html.erb
<h1>New Van</h1>

<%= render 'form', van: @van %>

<%= link_to 'Back', vans_path %>

app/views/vans/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Van year:</strong>
  <%= @van.vyear %>
</p>

<p>
  <strong>Van make:</strong>
  <%= @van.vmake %>
</p>

<p>
  <strong>Van model:</strong>
  <%= @van.vmodel %>
</p>

<p>
  <strong>Van Id:</strong>
  <%= @van.id %>
</p>

<p>
  <strong>Notes:</strong>
  <%= @van.notes %>
</p>

<p>
  <strong>Available:</strong>
  <%= @available %>
</p

<p>
  <strong>Rentals:</strong>
  <% @van.rentals.each do |rentalx| %>
    <p class="ps-1"> - 
      <%= rentalx.user.name %> Id:
      <%= rentalx.user.id %>
    </p>
    <p class="ps-4">Rented On: 
      <%= rentalx.rented_date %>
    </p>
    <% if rentalx.return_date.nil? || rentalx.return_date.to_date.future? %>
      <p class="ps-4"> Estimate Return Date: 
        <%= rentalx.estimate_return_date %>
      </p>
    <% else %>
      <p class="ps-4"> Returned On: 
        <%= rentalx.return_date %>
      </p>
    <% end %>
    <p class="ps-4">Rental Id: 
      <%= rentalx.id %>
    </p>
  <% end %>
</p>


<%= link_to 'Edit', edit_van_path(@van) %> |
<%= link_to 'Back', vans_path %>