config/routes.rb
Rails.application.routes.draw do
  
  resources :vans
  resources :books
  resources :rentals
  resources :items
  get 'user_management/assign_roles'
  patch 'user_management/update'
  get 'user_management/show'
  get 'user_management/edit'
  get 'user_management/create'
  post 'user_management/update'
  get 'user_management/new'
  post 'user_management/create'
  get 'item/available'
  resources :roles
  get 'home/index'
  get 'user_management/find_current_user'
  devise_for :users, :controllers => { :registrations => "users/registrations" }, :path_prefix => 'my'
  resources :users
  as :user do
    get "/register", to: "registrations#new", as: "register"
  end

  root to: "home#index"

end

app/models/rental.rb
class Rental < ApplicationRecord
  belongs_to :user
  belongs_to :rentable, polymorphic: true
  def rentable_sgid
    self.rentable&.to_signed_global_id
  end
  def rentable_sgid=(sgid)
    self.rentable = GlobalID::Locator.locate_signed(sgid)
  end

end

app/controllers/rentals_controller.rb
class RentalsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_rental, only: %i[ show edit update destroy ]

  def index
    @rentals = policy_scope(Rental, policy_scope_class: RentalPolicy::Scope)
    @users = User.all
    @items = Item.all
    authorize @user, policy_class: RentalPolicy
  end

  def show
    @user = User.where(id: @rental.user_id).first
    @rentable = helpers.get_rentable(@rental)
    authorize :dashboard, :show?
  end

  def new
    @rental = Rental.new
    set_rentable_list
    @role = current_user.roles.first
    authorize :dashboard, :new?
  end

  def edit
    authorize :dashboard, :edit?
  end

  def create
    set_rentable_list
    @rental = Rental.new(rental_params)
    authorize :dashboard, :create?
    respond_to do |format|
      if @rental.save
        format.html { redirect_to rental_url(@rental), notice: "Rental was successfully created." }
        format.json { render :show, status: :created, location: @rental }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @rental.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    authorize :dashboard, :update?
    respond_to do |format|
      if @rental.update(rental_params)
        format.html { redirect_to rental_url(@rental), notice: "Rental was successfully updated." }
        format.json { render :show, status: :ok, location: @rental }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @rental.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    authorize :dashboard, :destroy?
    @rental.destroy
    respond_to do |format|
      format.html { redirect_to rentals_url, notice: "Rental was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    def set_rental
      @rental = Rental.find(params[:id])
    end

    def set_rentable_list
      # rentable_list = []
      # puts "================================"
      # puts @user.rentables
      # puts "================================"
      # return rentable_list
    end

    def rental_params
      params.require(:rental).permit(:condition, :return_date, :estimate_return_date, :rented_date, :user_id, :rentable_type, :rentable_id)
    end
end

app/helpers/rentals_helper.rb
module RentalsHelper
    # def get_rentable(rnt)
    #   @rntable = rnt.rentable_type.constantize.find(rnt.rentable_id)
    #   return @rntable
    # end
end

app/views/rentals/_form.html.erb
<%= form_with(model: rental) do |form| %>
  <% if rental.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(rental.errors.count, "error") %> prohibited this rental from being saved:</h2>

      <ul>
        <% rental.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :condition %>
    <%= form.text_field :condition %>
  </div>

  <div class="field">
    <%= form.label :return_date %>
    <%= form.date_select(:return_date, include_blank: true) %>
  </div>

  <div class="field">
    <%= form.label :estimate_return_date %>
    <%= form.date_select(:estimate_return_date, default: 30.days.from_now) %>
  </div>

  <div class="field">
    <%= form.label :rented_date %>
    <%= form.date_select :rented_date %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :rentable_type %>
    <%= form.text_field :rentable_type %>
  </div>

  <div class="field">
    <%= form.label :rentable_id, "Rentable Id" %>
    <%= form.text_field :rentable_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>

<% end %>

app/views/rentals/edit.html.erb
<h1>Editing Rental</h1>

<%= render 'form', rental: @rental %>

<%= link_to 'Show', @rental %> |
<%= link_to 'Back', rentals_path %>

app/views/rentals/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Rentals</h1>

<table class="table">
  <thead>
    <tr>
      <th>Rental Id</th>
      <th>Condition</th>
      <th>Return date</th>
      <th>Estimate return date</th>
      <th>Rented date</th>
      <th>User's Name</th>
      <th>User's Id</th>
      <th>Rentable Type</th>
      <th>Rentable Id</th>
      <th>Rentable Name</th>

      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @rentals.each do |rental| %>
      <tr>
        <td><%= rental.id %></td>
        <td><%= rental.condition %></td>
        <td>
          <% if rental.return_date.nil? || rental.return_date.future? %>
            Currently out
          <% else %>
            <%= rental.return_date %>
          <% end %>
        </td>
        <td><%= rental.estimate_return_date %></td>
        <td><%= rental.rented_date %></td>
        <td><%= User.find(rental.user_id).name %></td>
        <td><%= User.find(rental.user_id).id %></td>
        <td><%= rental.rentable_type %></td>
        <td><%= rental.rentable_id %></td>
        <td><%= get_rentable(rental).name %></td>
        <td><%= link_to 'Show', rental %></td>
        <td><%= link_to 'Edit', edit_rental_path(rental) %></td>
        <td><%= link_to 'Destroy', rental, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Rental', new_rental_path %>

app/views/rentals/new.html.erb
<h1>New Rental</h1>

<%= render 'form', rental: @rental %>

<%= link_to 'Back', rentals_path %>

app/views/rentals/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <strong>Rental Id:</strong>
  <%= @rental.id %>
</p>
<p>
  <strong>Condition:</strong>
  <%= @rental.condition %>
</p>

<p>
  <strong>Return date:</strong>
  <% if @rental.return_date.nil? || @rental.return_date.future? %>
    Currently out
  <% else %>
    <%= @rental.return_date %>
  <% end %>
</p>

<p>
  <strong>Estimatte return date:</strong>
  <%= @rental.estimate_return_date %>
</p>

<p>
  <strong>Rented date:</strong>
  <%= @rental.rented_date %>
</p>

<p>
  <strong>User Id:</strong>
  <%= @user.id %>
</p>

<p>
  <strong>User Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Rentable Category:</strong>
  <%= get_rentable(@rental).model_name %>
</p>

<p>
  <strong>Rentable Id:</strong>
  <%= get_rentable(@rental).id %>
</p>

<p>
  <strong>Rentable Name:</strong>
  <%= get_rentable(@rental).name %>
</p>

<%= link_to 'Edit', edit_rental_path(@rental) %> |
<%= link_to 'Back', rentals_path %>