config/routes.rb
Rails.application.routes.draw do
  
  resources :vans
  resources :books
  resources :rentals
  resources :items
  get 'user_management/assign_roles'
  patch 'user_management/update'
  get 'user_management/show'
  get 'user_management/edit'
  get 'user_management/create'
  post 'user_management/update'
  get 'user_management/new'
  post 'user_management/create'
  get 'item/available'
  resources :roles
  get 'home/index'
  get 'user_management/find_current_user'
  devise_for :users, :controllers => { :registrations => "users/registrations" }, :path_prefix => 'my'
  resources :users
  as :user do
    get "/register", to: "registrations#new", as: "register"
  end

  root to: "home#index"

end

app/models/item.rb
class Item < ApplicationRecord
    has_many :rentals
    has_many :users, through: :rentals
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_item, only: %i[ show edit update destroy ]
  def index
    authorize :dashboard, :index?
    @items = Item.all
    @rentals = Rental.all
    @availables = is_available
  end

  def show
    authorize :dashboard, :show?
    @rentals = Rental.where(rentable_id: params[:id])
    @available = true
    @rentals.each do |rentalx|
      if rentalx.return_date.nil?
        @available = false
      else
        if rentalx.return_date.future?
          @available = false
        end
      end
    end
  end

  def new
    authorize :dashboard, :new?
    @item = Item.new
  end

  def edit
    authorize :dashboard, :edit?
  end

  def create
    authorize :dashboard, :create?
    @item = Item.new(item_params)
    respond_to do |format|
      if @item.save
        format.html { redirect_to item_url(@item), notice: "Item was successfully created." }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    authorize :dashboard, :update?
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to item_url(@item), notice: "Item was successfully updated." }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    authorize :dashboard, :destroy?
    @item = Item.find(params[:id])
    @item_rentals = Rental.where(item_id: @item.id)
    @item_rentals.each do |rentalx|
      rentalx.destroy
    end
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: "Item was successfully destroyed." }
      format.json { head :no_content }
    end
  end


  def is_available
    @items = Item.all
    available_items = []
    @items.each do |itemx|
      item_rentals = Rental.where(rentable_type: "Item", rentable_id: itemx.id)
      available = true
      item_rentals.each do |rentalx|
        if rentalx.return_date.nil? || rentalx.return_date.future?
          available = false
        end
      end
      available_items << available
    end
    return available_items
  end

  private
    def set_item
      @item = Item.find(params[:id])
    end

    def item_params
      params.require(:item).permit(:name, :description, :notes)
    end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<%= form_with(model: item) do |form| %>
  <% if item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
        <% item.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :notes %>
    <%= form.text_area :notes %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/items/edit.html.erb
<h1>Editing Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Items</h1>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Notes</th>
      <th>ID</th>
      <th>Availability</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @items.each_with_index do |item, index| %>
      <tr>
        <td><%= item.name %></td>
        <td><%= item.description %></td>
        <td><%= item.notes %></td>
        <td><%= item.id %></td>
        <td><%= @availables[index] %></td>
        <td><%= link_to 'Show', item %></td>
        <td><%= link_to 'Edit', edit_item_path(item) %></td>
        <td><%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Item', new_item_path %>

app/views/items/new.html.erb
<h1>New Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Back', items_path %>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @item.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @item.description %>
</p>

<p>
  <strong>Notes:</strong>
  <%= @item.notes %>
</p>

<p>
  <strong>Id:</strong>
  <%= @item.id %>
</p>

<p>
  <strong>Available:</strong>
  <%= @available %>
</p>

<p>
  <strong>Rentals:</strong>
  <% @item.rentals.each do |rentalx| %>
    <p class="ps-1"> - 
      <%= rentalx.user.name %> Id:
      <%= rentalx.user.id %>
    </p>
    <p class="ps-4">Rented On: 
      <%= rentalx.rented_date %>
    </p>
    <% if rentalx.return_date.nil? || rentalx.return_date.to_date.future? %>
      <p class="ps-4"> Estimate Return Date: 
        <%= rentalx.estimate_return_date %>
      </p>
    <% else %>
      <p class="ps-4"> Returned On: 
        <%= rentalx.return_date %>
      </p>
    <% end %>
    <p class="ps-4">Rental Id: 
      <%= rentalx.id %>
    </p>
  <% end %>
</p>


<%= link_to 'Edit', edit_item_path(@item) %> |
<%= link_to 'Back', items_path %>