config/routes.rb
Rails.application.routes.draw do
  
  resources :vans
  resources :books
  resources :rentals
  resources :items
  get 'user_management/assign_roles'
  patch 'user_management/update'
  get 'user_management/show'
  get 'user_management/edit'
  get 'user_management/create'
  post 'user_management/update'
  get 'user_management/new'
  post 'user_management/create'
  get 'item/available'
  resources :roles
  get 'home/index'
  get 'user_management/find_current_user'
  devise_for :users, :controllers => { :registrations => "users/registrations" }, :path_prefix => 'my'
  resources :users
  as :user do
    get "/register", to: "registrations#new", as: "register"
  end

  root to: "home#index"

end

app/controllers/user_management_controller.rb
class UserManagementController < ApplicationController
  before_action :authenticate_user!
  def assign_roles
    @users = policy_scope(User, policy_scope_class: UserManagementPolicy::Scope)
    @roles = Role.all
    authorize @user, policy_class: UserManagementPolicy
    @status = get_status
  end

  def show
    @user = User.find(params[:id])
    @roles = Role.all
    authorize @user.id, policy_class: UserManagementPolicy
  end

  def new
    @user = User.new
    @roles = Role.all
    authorize :dashboard, :new?
  end

  def edit
    @user = User.find(params[:id])
    @roles = policy_scope(Role, policy_scope_class: UserManagementPolicy::Scope)
    if @user.roles.first.nil?
      @role = default_role(@user)
      authorize @user, policy_class: UserManagementPolicy
    else
      @role = Role.where(name: @user.roles.first.name)
      authorize @user, policy_class: UserManagementPolicy
    end
  end

  def create
    @without_role = User.new(user_params.except(:role_id, :_method, :authenticity_token, :commit))
    @user = default_role(@without_role)
    @roles = Role.all
    authorize :dashboard, :create?
    respond_to do |format|
      if @user.save
        format.html { redirect_to user_management_show_path(id: @user.id), notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    if URI(request.referer).path == '/user_management/create' || URI(request.referer).path == '/user_management/new'
      @user = params[:user]
    else
      @user = User.find(params[:id])
    end
    if params[:role].present?
      @role = Role.where(id: params[:role][:role_id]).first
      authorize @role, policy_class: UserManagementPolicy
      @user.roles.clear
      @user.roles << @role
      respond_to do |format|
        format.html { redirect_to user_management_edit_path(id: @user), notice: "User's role was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      end
    else
      @role = Role.where(name: @user.roles.first)
      authorize @role, policy_class: UserManagementPolicy
      respond_to do |format|
        if @user.update(user_params.except(:role_id, :_method, :authenticity_token, :commit))
          format.html { redirect_to user_management_edit_path(id: @user), notice: "User was successfully updated." }
          format.json { render :show, status: :ok, location: @user }
        else
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: @user.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  def default_role(new_user)
    with_role = new_user
    with_role.roles << Role.where(name: 'Student').first
    return with_role
  end

  def find_current_user
    @current_user ||= User.find_by(id: session[:user_id])
    return @current_user
  end

  def get_status
    @users = policy_scope(User, policy_scope_class: UserManagementPolicy::Scope)
    @rentals = Rental.all
    stat_arr = []
    @users.each do |userx|
      if userx.rentals.present?
        users_late_objects = ""
        userx.rentals.each_with_index do |rentalx, index|
          if rentalx.estimate_return_date.nil? || rentalx.estimate_return_date.past?
            if rentalx.return_date.nil?
              users_late_objects << helpers.get_rentable(rentalx).name
              if index != userx.rentals.size - 1
                users_late_objects << ", "
              end
            end
          end
        end
        if users_late_objects.empty?
          stat_arr << "No Late Objects"
        else
          stat_arr << users_late_objects
        end
      else
        stat_arr << "No Rented Objects"
      end
    end
    return stat_arr
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end
    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:role_id, :_method, :role, :id, :email, :password, :id_number, :name, :phone, :password_confirmation, :authenticity_token, :commit)
    end

    def update_params
      params.permit(:role_id, :user, :_method, :role, :id, :email, :password, :id_number, :name, :phone, :password_confirmation, :authenticity_token, :commit)
    end
end

app/helpers/user_management_helper.rb
module UserManagementHelper
    
end

app/views/user_management/_form.html.erb
<%= form_with(model: @user, url: path) do |form| %>

  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>
      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <% if request.path == "/user_management/new" %>

    <div class="field">
      <%= form.label :password %>
      <%= form.text_field :password %>
    </div>

    <div class="field">
      <%= form.label :password_confirmation %>
      <%= form.text_field :password_confirmation %>
    </div>

  <% end %>

  <div class="field">
    <%= form.label :id_number %>
    <%= form.text_field :id_number %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :phone %>
    <%= form.text_field :phone %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>


<%= form_with(model: @role, url: path) do |form| %>
  <% if request.path == "/user_management/edit" %>
    <div class="field">
      <%= form.label :role %>
      <% @roles.each do |role| %>
        <div class="form-check">
          <% if user.roles.index(role) %>
            <%= form.radio_button(:role_id, role.id, :checked => 'checked') %>
            <%= form.label(role.id, role.name) %>
          <% else %>
            <%= form.radio_button(:role_id, role.id) %>
            <%= form.label(role.id, role.name) %>
          <% end %>
        </div>
      <% end %>
    </div>

    <div class="actions">
      <%= form.submit "Update User's Role"%>
    </div>
  <% end %>
<% end %>

app/views/user_management/assign_roles.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>School ID</th>
      <th>Phone Number</th>
      <th>E-mail Account</th>
      <th>Id</th>
      <th>Role</th>
      <th>Role Id</th>
      <th>Late Objects</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each_with_index do |userx, index| %>
      <tr>
        <td> <%= userx.name %> </td>
        <td> <%= userx.id_number %> </td>
        <td> <%= userx.phone %> </td>
        <td> <%= userx.email %> </td>
        <td> <%= userx.id %> </td>
        <% userx.roles.each do |rolex| %>
          <td> <%= rolex.name %> </td>
          <td> <%= rolex.id %> </td>
        <% end %>
        <% if @status[index] == "No Rented Objects" %>
          <td> <%= @status[index] %> </td>
        <% elsif @status[index] == "No Late Objects" %>
          <td class="text-primary"> <%= @status[index] %> </td>
        <% else %>
          <td class="text-danger"> <%= @status[index] %> </td>
        <% end %>
        <td><%= link_to 'Show', user_management_show_path(id: userx.id) %></td>
        <td><%= link_to 'Edit', user_management_edit_path(id: userx.id) %></td>
        <td><%= link_to "Delete", user_registration_path(userx, id: userx.id), :method => :delete, data: { confirm: 'Are you sure you want to delete this user?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', user_management_new_path %>

app/views/user_management/create.html.erb
<h1>Create User</h1>

<%= render 'form', user: @user, path: user_management_create_path %>


<%= link_to 'Back', user_management_assign_roles_path %>

app/views/user_management/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user, path: user_management_update_path(id: @user.id) %>

<%= link_to 'Show', user_management_show_path(id: @user.id) %> |
<%= link_to 'Back', user_management_assign_roles_path %>

app/views/user_management/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user, path: user_management_create_path %>


<%= link_to 'Back', user_management_assign_roles_path %>

app/views/user_management/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>School Id:</strong>
  <%= @user.id_number %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @user.phone %>
</p>

<p>
  <strong>E Mail:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Role:</strong>
  <% @user.roles.each do |rolex| %>
    <p class="ps-1"> - 
      <%= rolex.name %>
    </p>
  <% end %>
</p>

<p>
  <strong>Id:</strong>
  <%= @user.id %>
</p>

<p>
  <strong>Rentals:</strong>
  <% @user.rentals.each do |rentalx| %>
    <p class="ps-1"> - 
      <%= rentalx.rentable_type %> Id:
      <%= rentalx.rentable_id %>
    </p>
    <p class="ps-4">Name: 
      <%= get_rentable(rentalx).name %>
    </p>
    <p class="ps-4">Rented On: 
      <%= rentalx.rented_date %>
    </p>
    <% if rentalx.return_date.nil? || rentalx.return_date.to_date.future? %>
      <p class="ps-4"> Estimate Return Date: 
        <%= rentalx.estimate_return_date %>
      </p>
    <% else %>
      <p class="ps-4"> Returned On: 
        <%= rentalx.return_date %>
      </p>
    <% end %>
    <p class="ps-4">Rental Id: 
      <%= rentalx.id %>
    </p>
  <% end %>
</p>

<%= link_to 'Edit', user_management_edit_path(id: @user.id) %> |
<%= link_to 'Back', user_management_assign_roles_path %>